### ISSUE TITLE
Fails to compile on kernel 4.8

### ISSUE THREAD

**Issue by connorimes** [LLNL/msr-safe#11]
Running `make` results in the following:

```sh
make -C /lib/modules/4.8.0-26-generic/build M=/local/msr-safe modules 
make[1]: Entering directory '/usr/src/linux-headers-4.8.0-26-generic'
  CC [M]  /local/msr-safe/msr_entry.o
/local/msr-safe/msr_entry.c: In function 'msr_seek':
/local/msr-safe/msr_entry.c:61:19: error: 'struct inode' has no member named 'i_mutex'; did you mean 'i_mode'?
  mutex_lock(&inode->i_mutex);
                   ^~
/local/msr-safe/msr_entry.c:74:21: error: 'struct inode' has no member named 'i_mutex'; did you mean 'i_mode'?
  mutex_unlock(&inode->i_mutex);
                     ^~
scripts/Makefile.build:289: recipe for target '/local/msr-safe/msr_entry.o' failed
make[2]: *** [/local/msr-safe/msr_entry.o] Error 1
Makefile:1489: recipe for target '_module_/local/msr-safe' failed
make[1]: *** [_module_/local/msr-safe] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.8.0-26-generic'
Makefile:31: recipe for target 'all' failed
make: *** [all] Error 2
```
