### PR TITLE
Use down_write/up_write in kernel 4.7 and newer in place of mutex_loc…

### LINKED ISSUE #11: Fails to compile on kernel 4.8
Running `make` results in the following:

```sh
make -C /lib/modules/4.8.0-26-generic/build M=/local/msr-safe modules 
make[1]: Entering directory '/usr/src/linux-headers-4.8.0-26-generic'
  CC [M]  /local/msr-safe/msr_entry.o
/local/msr-safe/msr_entry.c: In function 'msr_seek':
/local/msr-safe/msr_entry.c:61:19: error: 'struct inode' has no member named 'i_mutex'; did you mean 'i_mode'?
  mutex_lock(&inode->i_mutex);
                   ^~
/local/msr-safe/msr_entry.c:74:21: error: 'struct inode' has no member named 'i_mutex'; did you mean 'i_mode'?
  mutex_unlock(&inode->i_mutex);
                     ^~
scripts/Makefile.build:289: recipe for target '/local/msr-safe/msr_entry.o' failed
make[2]: *** [/local/msr-safe/msr_entry.o] Error 1
Makefile:1489: recipe for target '_module_/local/msr-safe' failed
make[1]: *** [_module_/local/msr-safe] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.8.0-26-generic'
Makefile:31: recipe for target 'all' failed
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by connorimes**
This patch seems to fix #11 but somebody with more kernel experience should verify that the locking approach is correct.  Cheers.

### CODE REVIEW

**Comment by connorimes** [comment]
@slabasan - your commit fb57ac6 included a lot of whitespace changes to files and introduced conflicts into this PR.  If this is intentional, I can rebase and update the PR.  However, please be aware that such sweeping changes to files tend to introduce conflicts in forks/branches/PRs.  If this was a result of an IDE performing autoformatting, you may want to turn off the feature.

**Comment by slabasan** [comment]
@connorimes Thanks for the catch. Didn't intend on changing the tabs to spaces. I've restored these files and your PR no longer has conflicts.

**Comment by connorimes** [comment]
Now you rebased a commit in a public repository, causing PR #21 to contain your old commit even though it doesn't show a conflict.  Hopefully no other forks' history was damaged.  Live and learn :).
