### PR TITLE
Use inode_lock and inode_unlock in supported kernel versions, mutex_l…

### LINKED ISSUE #11: Fails to compile on kernel 4.8
Running `make` results in the following:

```sh
make -C /lib/modules/4.8.0-26-generic/build M=/local/msr-safe modules 
make[1]: Entering directory '/usr/src/linux-headers-4.8.0-26-generic'
  CC [M]  /local/msr-safe/msr_entry.o
/local/msr-safe/msr_entry.c: In function 'msr_seek':
/local/msr-safe/msr_entry.c:61:19: error: 'struct inode' has no member named 'i_mutex'; did you mean 'i_mode'?
  mutex_lock(&inode->i_mutex);
                   ^~
/local/msr-safe/msr_entry.c:74:21: error: 'struct inode' has no member named 'i_mutex'; did you mean 'i_mode'?
  mutex_unlock(&inode->i_mutex);
                     ^~
scripts/Makefile.build:289: recipe for target '/local/msr-safe/msr_entry.o' failed
make[2]: *** [/local/msr-safe/msr_entry.o] Error 1
Makefile:1489: recipe for target '_module_/local/msr-safe' failed
make[1]: *** [_module_/local/msr-safe] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.8.0-26-generic'
Makefile:31: recipe for target 'all' failed
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by connorimes**
…ock and mutex_unlock not available in current versions

This PR fixes #11 and supersedes PRs #12 and #21.  #12 would work fine, but we might as well use the abstractions that `inode_lock` and `inode_unlock` provide in `linux/fs.h` since v4.5 (thanks @maiterth for finding these functions).  #21's git history diverged after a rebase on master, and doesn't appear to be implemented correctly anyway.

### CODE REVIEW

**Comment by connorimes** [comment]
Is it possible to get this reviewed and merged?  It would make some of my workflow easier.  Thanks.

**Comment by slabasan** [comment]
@connorimes @cmcantalupo @bgeltz Apologies for the delay. We're working to get this integrated asap. There should be no problems with the merge, just need to collect a review from a few others. Thanks so much for your patience. I will try to keep you as updated as I can.

**Comment by slabasan** [comment]
@connorimes I've merged the fix for kernels v4.5 and newer. I'll leave this PR open and close the earlier ones #12 and #21.

**Comment by connorimes** [comment]
@slabasan Thanks for getting the fix in.  Is there a reason to keep the PR open?  Also, did you squash my commit?  I don't see it in the git log for `master`.

**Comment by slabasan** [comment]
@connorimes We'll keep it open for a bit in case any issues pop up. Your commit was squashed into `5adfe7`.

**Comment by connorimes** [comment]
OK, well the most important thing is that the fix is available.  Thanks.
